name: build
on: [pull_request]
jobs:
  code_analysis:
    name: code_analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2']
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: cache vendor/bundle
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
      - name: Display ruby version
        run: ruby -v
      - name: Display rails version
        run: bundle exec rails -v
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run haml-lint
        run: bundle exec haml-lint
      - name: Run brakeman
        run: bundle exec brakeman
      - name: Run reek
        run: bundle exec reek
  rspec:
    name: rspec
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2']
        rails: ['7_0', '7_1']
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: cache vendor/bundle
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
      - name: Display ruby version
        run: ruby -v
      - name: Display rails version
        run: bundle exec rails -v
      - name: Run rspec
        run: bundle exec rspec
